import "./globals.css";
// import { Space_Grotesk } from "next/font/google";
import { Inter } from "next/font/google";

// adding a font from google by just adding the package of next js

// components
import Navigation from "./components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// links
const links = [
  {
    label: "Home",
    route: "/",
  },
  {
    label: "About",
    route: "/about",
  },
  {
    label: "Posts",
    route: "/posts",
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation links={links} />
        {children}
      </body>
    </html>
  );
}
